"""Added user_profile, user_garden, and garden_type tables

Revision ID: 1bc9a15545d9
Revises: a4caff62999c
Create Date: 2025-02-17 17:00:00.579599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc9a15545d9'
down_revision = 'a4caff62999c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('descripton', sa.Text(), nullable=True),
    sa.Column('ideal_soil_type', sa.String(length=100), nullable=True),
    sa.Column('space_requirements', sa.String(length=100), nullable=True),
    sa.Column('maintenance_level', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_garden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('garden_name', sa.String(length=100), nullable=True),
    sa.Column('garden_type_id', sa.Integer(), nullable=True),
    sa.Column('is_community_garden', sa.Boolean(), nullable=True),
    sa.Column('is_rooftop_garden', sa.Boolean(), nullable=True),
    sa.Column('garden_size', sa.String(length=50), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('water_source', sa.String(length=100), nullable=True),
    sa.Column('pest_protection', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garden_type_id'], ['garden_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_hardiness_zone', sa.String(length=10), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('has_irrigation', sa.Boolean(), nullable=True),
    sa.Column('sunlight_hours', sa.Float(), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('user_garden')
    op.drop_table('garden_type')
    # ### end Alembic commands ###
