"""Added plant_hardiness_zone, garden_dimensions, preferred_plants, and current_plants to user_garden.

Revision ID: 3f5abc52da81
Revises: 1bc9a15545d9
Create Date: 2025-02-18 16:21:11.282759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5abc52da81'
down_revision = '1bc9a15545d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garden_dimensions', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('plant_hardiness_zone', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('preferred_plants', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_plants', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.drop_column('current_plants')
        batch_op.drop_column('preferred_plants')
        batch_op.drop_column('plant_hardiness_zone')
        batch_op.drop_column('garden_dimensions')

    # ### end Alembic commands ###
