"""Change GardenType.name to Enum type

Revision ID: 71fe3b9b4aa8
Revises: 0700de7eaf6a
Create Date: 2025-03-03 17:24:41.613786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fe3b9b4aa8'
down_revision = '0700de7eaf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('RAISED_BED', 'CONTAINER', 'TRADITIONAL_ROW', 'GREENHOUSE', 'VERTICAL', 'HYDROPONIC', 'PERMACULTURE', 'COMMUNITY', 'WILDLIFE_GARDEN', 'ROOFTOP', name='gardentypeenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Enum('RAISED_BED', 'CONTAINER', 'TRADITIONAL_ROW', 'GREENHOUSE', 'VERTICAL', 'HYDROPONIC', 'PERMACULTURE', 'COMMUNITY', 'WILDLIFE_GARDEN', 'ROOFTOP', name='gardentypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
