"""Reinitializing database schema

Revision ID: a4caff62999c
Revises: 
Create Date: 2025-02-13 18:34:42.583219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4caff62999c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('hardiness_min', sa.String(length=10), nullable=True),
    sa.Column('hardiness_max', sa.String(length=10), nullable=True),
    sa.Column('best_temperature_min', sa.Float(), nullable=True),
    sa.Column('best_temperature_max', sa.Float(), nullable=True),
    sa.Column('requires_greenhouse', sa.Boolean(), nullable=True),
    sa.Column('suitable_for_containers', sa.Boolean(), nullable=True),
    sa.Column('growing_season', sa.String(length=50), nullable=True),
    sa.Column('water_needs', sa.String(length=20), nullable=True),
    sa.Column('sunlight', sa.String(length=50), nullable=True),
    sa.Column('space_required', sa.String(length=20), nullable=True),
    sa.Column('sowing_method', sa.String(length=50), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('row_spacing', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('plant')
    # ### end Alembic commands ###
