"""Added user_garden_plant table

Revision ID: da915219fd44
Revises: 3f5abc52da81
Create Date: 2025-02-18 19:57:50.441734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da915219fd44'
down_revision = '3f5abc52da81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_garden_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('planted_at', sa.DateTime(), nullable=True),
    sa.Column('expected_harvest_date', sa.DateTime(), nullable=True),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['user_garden.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_garden_plant')
    # ### end Alembic commands ###
