"""Added GardenType enum for consistency.

Revision ID: f6946342659e
Revises: eec90dada1b7
Create Date: 2025-02-19 19:15:48.436203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6946342659e'
down_revision = 'eec90dada1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('RAISED_BED', 'CONTAINER', 'TRADITIONAL_ROW', 'GREENHOUSE', 'VERTICAL', 'HYDROPONIC', 'PERMACULTURE', 'COMMUNITY', 'WILDLIFE_GARDEN', 'ROOFTOP', name='gardentype'),
               existing_nullable=False)

    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.alter_column('garden_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.alter_column('garden_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('garden_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Enum('RAISED_BED', 'CONTAINER', 'TRADITIONAL_ROW', 'GREENHOUSE', 'VERTICAL', 'HYDROPONIC', 'PERMACULTURE', 'COMMUNITY', 'WILDLIFE_GARDEN', 'ROOFTOP', name='gardentype'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
