"""Add grid dimensions and map position fields

Revision ID: ff67b56add40
Revises: 5fc6fec45dfd
Create Date: 2026-04-01 16:24:07.031610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff67b56add40'
down_revision = '5fc6fec45dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grid_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grid_cols', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_garden_plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('col', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_garden_plant', schema=None) as batch_op:
        batch_op.drop_column('col')
        batch_op.drop_column('row')

    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.drop_column('grid_cols')
        batch_op.drop_column('grid_rows')

    # ### end Alembic commands ###
